M48
; DRILL file {KiCad 7.0.7} date 2023 September 10, Sunday 14:40:33
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-10T14:40:33-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X6.6504Y-3.3
X6.9504Y-3.3
X7.7Y-3.3
X8.1Y-3.3
T2
X7.0Y-2.6
X7.1Y-2.6
X7.7Y-2.6
X7.8Y-2.6
T0
M30
